#!/usr/bin/env lua

local fmt = string.format
local concat = table.concat

local input = "/usr/include/linux/input-event-codes.h"
local generated_from = fmt("-- Generated by %q from %q", arg[0], input)

---@type {ABS:{},BTN:{},EV:{},INPUT_PROP:{},KEY:{},LED:{},MSC:{},REL:{},REP:{},SND:{},SW:{},SYN:{}}
local ecodes_by_prefix = {}

-- stylua: ignore
local prefixes = {
  ABS        = false,
  BTN        = true,
  EV         = true,
  INPUT_PROP = false,
  KEY        = true,
  LED        = false,
  MSC        = false,
  REL        = true,
  REP        = false,
  SND        = false,
  SW         = false,
  SYN        = true,
}

local function readfile(path)
  local file = assert(io.open(path, "r"))
  local text = file:read("*a")
  file:close()
  return text
end

local function writefile(path, ...)
  local file = assert(io.open(path, "w"))
  file:write(...)
  file:close()
end

local function collect_keys_values(t)
  local keys, values = {}, {}
  for k, v in pairs(t) do
    keys[#keys + 1], values[#values + 1] = k, v
  end
  return keys, values
end

local function tbl_flatten(t)
  local out = {}
  for _, child in pairs(t) do
    if type(child) == "table" then
      for key, value in pairs(child) do
        out[key] = value
      end
    end
  end
  return out
end

local function spairs(t)
  local keys = collect_keys_values(t)
  table.sort(keys)
  local i = 0
  return function()
    i = i + 1
    local k = keys[i]
    return k, t[k]
  end
end

local function max_string_width(ls)
  local width = 0
  for _, v in ipairs(ls) do
    local text = tostring(v)
    if #text > width then
      width = #text
    end
  end
  return width
end

local function ljust(text, width)
  return ("%-" .. width .. "s"):format(text)
end

local function rjust(text, width)
  return ("%" .. width .. "s"):format(text)
end

local function strip_comment(line)
  return (line:gsub("/%*.-%*/", ""):gsub("//.*$", ""))
end

---@type fun(v:table<string,integer>):string
local function stringify(t)
  local parts = {}
  local keys, values = collect_keys_values(t)
  local kw = max_string_width(keys)
  local vw = max_string_width(values)
  for k, v in spairs(t) do
    parts[#parts + 1] = fmt("%s = %s", ljust(k, kw), rjust(v, vw))
  end
  return fmt("{\n  %s\n}", concat(parts, ",\n  "))
end

local function wanted(name)
  for prefix, enabled in pairs(prefixes) do
    if enabled and name:sub(1, #prefix + 1) == prefix .. "_" then
      return true
    end
  end
  return false
end

-- stylua: ignore
local function normalize_expr(expr)
  return expr
    :gsub("^%s+", "")
    :gsub("%s+$", "")
    :gsub("^[%(]+", "")
    :gsub("[%)]+$", "")
end

local function parse_number(expr)
  local sign = 1
  expr = normalize_expr(expr)

  if expr:sub(1, 1) == "-" then
    sign = -1
    expr = expr:sub(2)
  end

  local hex = expr:match("^0[xX](%x+)$")
  if hex then
    return sign * tonumber(hex, 16)
  end

  if expr:match("^%d+$") then
    return sign * tonumber(expr, 10)
  end
end

local function resolve_expr(expr, resolved_values)
  expr = normalize_expr(expr)

  local number = parse_number(expr)
  if number ~= nil then
    return number
  end

  local alias = expr:match("^([A-Z0-9_]+)$")
  if alias then
    return resolved_values[alias]
  end

  local left, op, right = expr:match("^%(?%s*([A-Z0-9_]+)%s*([%+%-])%s*(%d+)%s*%)?$")
  if left and resolved_values[left] then
    if op == "+" then
      return resolved_values[left] + tonumber(right)
    end
    return resolved_values[left] - tonumber(right)
  end
end

---@type fun(text:string):(ecodes:table<string,integer>)
local function parse_defines(text)
  local resolved_values = {}
  local unresolved = {}

  for raw_line in text:gmatch("[^\r\n]+") do
    local line = strip_comment(raw_line)
    local name, expr = line:match("^%s*#define%s+([A-Z0-9_]+)%s+(.+)%s*$")
    if name and wanted(name) then
      expr = normalize_expr(expr)
      if not expr:find("%s") then
        local v = resolve_expr(expr, resolved_values)
        if v then
          resolved_values[name] = v
        else
          unresolved[name] = expr
        end
      end
    end
  end

  local changed = true
  while changed do
    changed = false
    for name, expr in pairs(unresolved) do
      local v = resolve_expr(expr, resolved_values)
      if v then
        resolved_values[name] = v
        changed = true
      end
    end
  end

  return resolved_values
end

---@type fun(ecodes:table<string,integer>):{[string]:table<string,integer>}
local function group_by_prefix(ecodes)
  local groups = {}
  for prefix in pairs(prefixes) do
    groups[prefix] = {}
  end

  for name, code in pairs(ecodes) do
    for prefix in pairs(prefixes) do
      if name:sub(1, #prefix + 1) == prefix .. "_" then
        groups[prefix][name] = code
        break
      end
    end
  end

  return groups
end

local function load_ecodes()
  local ecodes = parse_defines(readfile(input))
  local groups = group_by_prefix(ecodes)
  for prefix, g in pairs(groups) do
    ecodes_by_prefix[prefix] = g
  end
end

local function write_runtime_ecodes(path)
  local ecodes = tbl_flatten(ecodes_by_prefix)
  local text = {
    generated_from,
    "",
    "-- stylua: ignore",
    fmt("return %s", stringify(ecodes)),
  }
  writefile(path, concat(text, "\n"), "\n")
end

local function write_ecodes_class(path)
  local ecodes = tbl_flatten(ecodes_by_prefix)
  local text = {
    "---@meta evdev.ecodes",
    "",
    generated_from,
    "",
    "---@class evdev.ecodes",
    fmt("local M = %s", stringify(ecodes)),
    "",
    "return M",
  }
  writefile(path, concat(text, "\n"), "\n")
end

local function write_ecodes_enums(path)
  local text = {
    "---@meta _",
    "",
    generated_from,
  }

  for prefix, ecodes in spairs(ecodes_by_prefix) do
    if prefixes[prefix] then
      text[#text + 1] = ""
      text[#text + 1] = fmt("---@enum evdev.ecodes.%s", prefix:lower())
      text[#text + 1] = fmt("local %s = %s", prefix, stringify(ecodes))
    end
  end

  writefile(path, concat(text, "\n"), "\n")
end

local function main()
  load_ecodes()
  write_runtime_ecodes("src/evdev/ecodes.lua")
  write_ecodes_class("types/ecodes.d.lua")
  write_ecodes_enums("types/_enums.d.lua")
end

main()
