name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      stylua:
        description: "StyLua"
        type: boolean
        default: false
      luacheck:
        description: "Luacheck"
        type: boolean
        default: false
      markdownlint:
        description: "Markdownlint"
        type: boolean
        default: false
      tests:
        description: "Tests"
        type: boolean
        default: false
      docs:
        description: "Docs"
        type: boolean
        default: false
      release-please:
        description: "Release Please"
        type: boolean
        default: false
      publish-dev:
        description: "Publish dev"
        type: boolean
        default: false
      publish-release:
        description: "Publish release"
        type: boolean
        default: false

permissions:
  contents: write
  pull-requests: write

jobs:
  ci:
    uses: BlueLua/.github/.github/workflows/ci.yml@main
    secrets: inherit
    # prettier-ignore
    with:
      run: |
        echo 'KERNEL=="event*", SUBSYSTEM=="input", MODE="0666"' | sudo tee /etc/udev/rules.d/99-evdev-test.rules
        sudo udevadm control --reload-rules
        sudo modprobe uinput || true
        sudo udevadm trigger --subsystem-match=input || true
        test -e /dev/uinput
        sudo chmod 666 /dev/uinput

      linux:   true
      macos:   false
      windows: false

      stylua:       ${{ inputs.stylua       || false }}
      luacheck:     ${{ inputs.luacheck     || false }}
      markdownlint: ${{ inputs.markdownlint || false }}

      tests: ${{ inputs.tests || false }}
      docs:  ${{ inputs.docs  || false }}

      release-please:  ${{ inputs.release-please  || false }}
      publish-dev:     ${{ inputs.publish-dev     || false }}
      publish-release: ${{ inputs.publish-release || false }}
